In [1]:
import pandas as pd
import numpy as np

In [16]:
path = '../data/normal_data.csv'
df = pd.read_csv(path, low_memory=False)

In [17]:
df.head()

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type,uid
0,1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,...,0,-,-,-,bad_TCP_checksum,-,F,0,normal,NaN
1,1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,...,0,-,-,-,-,-,-,0,normal,NaN
2,1554198359,192.168.1.152,1880,192.168.1.152,51782,tcp,-,0.000000,0,0,...,0,-,-,-,bad_TCP_checksum,-,F,0,normal,NaN
3,1554198359,192.168.1.152,34296,192.168.1.152,10502,tcp,-,0.000000,0,0,...,0,-,-,-,-,-,-,0,normal,NaN
4,1554198362,192.168.1.152,46608,192.168.1.190,53,udp,dns,0.000549,0,298,...,0,-,-,-,bad_UDP_checksum,-,F,0,normal,NaN

In [19]:
df['uid'].value_counts()

uid
C80vbe4UwGtsBS5qD9    1
CfRGzy3iKjpLMjVm8     1
Cg4PFI3UhJJUYBULQc    1
CkghCF48b1NfQvFu27    1
Cn3cAu1t0RVdYjmcke    1
                     ..
CfYElROz8oVS0DpL8     1
C1NGvBmt7NP9ALZRd     1
C4rsmo1cXLYi8mWHla    1
CvvgM84cDCJhrwKwLa    1
CYctQO1uYBPtEOMNml    1
Name: count, Length: 13473, dtype: int64

In [24]:
df['src_ip'].value_counts()

src_ip
192.168.1.195      160347
192.168.1.190      157579
192.168.1.152      136892
192.168.1.79        85933
192.168.1.180       51406
                    ...
203.171.203.0           1
108.170.247.65          1
108.170.247.33          1
203.171.203.1           1
199.115.158.193         1
Name: count, Length: 23360, dtype: int64

In [7]:
df['dns_qclass'].value_counts()

dns_qclass
0        642598
1        151148
32769      2634
Name: count, dtype: int64

In [8]:
df['http_status_code'].value_counts()

http_status_code
0      796127
200       182
206        58
302         9
304         3
101         1
Name: count, dtype: int64

In [12]:
df['duration'].max()

np.float64(85274.3546)

In [13]:
q75 = df['duration'].quantile(0.75)
q25 = df['duration'].quantile(0.25)
print(f"Q25: {q25}, Q75: {q75}, IQR: {q75 - q25}")

Q25: 0.0, Q75: 0.036288, IQR: 0.036288

In [2]:
path = '../data/Processed_Network_dataset/Network_dataset_1.csv'
df = pd.read_csv(path)

C:\Users\ACER\AppData\Local\Temp\ipykernel_2932\1207260569.py:2: DtypeWarning: Columns (0: src_bytes) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

In [3]:
df.head()

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
0,1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1,1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
2,1554198359,192.168.1.152,1880,192.168.1.152,51782,tcp,-,0.000000,0,0,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
3,1554198359,192.168.1.152,34296,192.168.1.152,10502,tcp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
4,1554198362,192.168.1.152,46608,192.168.1.190,53,udp,dns,0.000549,0,298,...,0,0,-,-,-,bad_UDP_checksum,-,F,0,normal

In [10]:
df.shape

(1000000, 46)

In [5]:
df['type'].nunique()

2

In [11]:
filtered_ = df.groupby('type').apply(
    lambda g: g.sample(n = min(len(g),1000), random_state=42  )
).reset_index(drop=True)

In [12]:
filtered_.shape

(2000, 45)

In [15]:
sampled = []
for t, group in df.groupby('type'):
    sampled.append(group.sample(n=min(len(group), 1000), random_state=42))
filtered = pd.concat(sampled, ignore_index=True)
print(filtered['type'].value_counts())  # verify type column is there

type
normal      1000
scanning    1000
Name: count, dtype: int64